<div style="font-family: Arial;
font-size: 14px;
padding: 20px 10px;
background: #eeeeee">
	<div style="width:600px; margin: 0 auto">
		<div style="background: #1a1a1a url(../img/back_00.png) no-repeat center;
		font-size: 18px;
		font-family: 'SegoeUI',Arial;
		font-weight: lighter;
		padding: 8px 10px;
		color: #FFF;
		height: 25px;
		z-index: 100;">
		<?php echo $this->title; ?>
		</div>
		<div style="padding: 10px;
		background: #FFF;
		min-height:150px">
		<?php echo $this->content; ?>
		</div>
	</div>
</div>