<h1>Termos de uso Trash Of WEB</h1>

<p>O Trash Of WEB é um serviço de interação e comunicação de usuários da internet em forma de postagens e comentários.</p>

<p>Os usuários poderá publicar textos com limite de 200 caracteres e comentar essas publicações com limite de 200 caracteres.</p>

<p>As publicações são caracterizada como somente texto, idem para os comentários.</p>

<strong>Conteúdo</strong></br>
A página inicial é dividia em duas características:</br>
Posts da rede: é mostrado os últimos posts do pais em que o usuário está cadastrado</br>
Posts dos amigos: é mostrado os últimos posts de seus seguidores</br>
</br>
<strong>Privacidade</strong></br>
<p>Toda publicação tem caráter público, qualquer pessoa de fora da rede social pode ter acesso as publicações, é necessário ter bastante cautela em suas publicações.</p>

<p>Todo post está suscetível à um comentário de qualquer pessoa.</p>

<p>Os comentários e posts não deve possuir conteúdo de caráter criminoso.</p>

Armazenamos os seguintes dados dos usuários:</br>
<p>País, Fuso Horário, Idioma, Imagem, Nome, Email, Data Cadastro, Data do último acesso</p>

Possuímos 2 modalidades de envio de e-mails:</br>
Mais importante (obrigatória):</br>
Alteração de dados, Informações de manutenção, Seguidores, Avisos sobre acesso</br>
Todas:</br>
Inclui as 'Mais importantes' e há um envio a cada 1hr com todas a notificações não vista.</br>
</br>
<strong>Segurança</strong></br>
<p>Os perfis, posts e comentários podem ser removidos por ação judicial ou por conter conteúdo inadequado.</p>

<strong>Publicidade</strong></br>
No site haverá publicidades em posições estratégicas. as publicidades servirá para gerar renda para manter o site.</br>
O usuário poderá fazer uma doação ou ajudar em manutenção no site assim, ela não verá mais propagandas.</br>
